GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmVrdzE5OTZAZ21haWwuY29tIiwicGFzc3dvcmQiOiJtYXJlazE5OTYiLCJpYXQiOjE1ODY2NDA3NDJ9.eo35pz3Q68H76ZcRUGgRh_7KgENu-HHAQ7DigTO9J1E


###

Send Request
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"marekwino12@gmail.com"
}